project_id = "gfvqympaaglkplzbocbl"

[functions.seed-test-users]
verify_jwt = false

[functions.validate-item-price]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.admin-ai-chat]
verify_jwt = false

