// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfvqympaaglkplzbocbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmdnF5bXBhYWdsa3BsemJvY2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MTM2NTYsImV4cCI6MjA4NzI4OTY1Nn0.URR_2cpEO5xMsFwDGfELuYIn4g6Q8bIYKd4V-flBXhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});